export const CHECK_PAYMODE = 'CHECK_PAYMODE';
export const RECEIVE_PAYMODES = 'RECEIVE_PAYMODES';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const CHECK_COUPON = 'CHECK_COUPON';
export const RECEIVE_COUPONS = 'RECEIVE_COUPONS';
